language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
# deploy:
#   edge:
#     branch: v1.8.47
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   on:
#     branch: master
#   local_dir: ./build
